/// 実績の表示名と説明文。
///
/// achievementEarned 通知の API レスポンスには実績ID（例: `notes1`）しか含まれず、
/// 表示名はサーバーから取得できない。Misskey 公式クライアントもフロントエンドの
/// 言語ファイルに対応表を持っているため、同様にアプリ側で保持する。
///
/// 出典: Misskey v2026.6.0 の `locales/ja-JP.yml`（`_achievements._types`）。
/// ID一覧はバックエンドの `ACHIEVEMENT_TYPES`（`packages/backend/src/models/UserProfile.ts`）と一致することを確認済み。
/// Misskey に実績が追加された場合はここに追記する。未登録のIDは呼び出し側でIDをそのまま表示する。
const Map<String, ({String title, String description})> achievementTypes = {
  'notes1': (title: 'just setting up my msky', description: '初めてノートを投稿した'),
  'notes10': (title: 'いくつかのノート', description: 'ノートを10回投稿した'),
  'notes100': (title: 'たくさんのノート', description: 'ノートを100回投稿した'),
  'notes500': (title: 'ノートまみれ', description: 'ノートを500回投稿した'),
  'notes1000': (title: 'ノートの山', description: 'ノートを1,000回投稿した'),
  'notes5000': (title: '湧き出るノート', description: 'ノートを5,000回投稿した'),
  'notes10000': (title: 'スーパーノート', description: 'ノートを10,000回投稿した'),
  'notes20000': (title: 'ニードモアノート', description: 'ノートを20,000回投稿した'),
  'notes30000': (title: 'ノートノートノート', description: 'ノートを30,000回投稿した'),
  'notes40000': (title: 'ノート工場', description: 'ノートを40,000回投稿した'),
  'notes50000': (title: 'ノートの惑星', description: 'ノートを50,000回投稿した'),
  'notes60000': (title: 'ノートクエーサー', description: 'ノートを60,000回投稿した'),
  'notes70000': (title: 'ブラックノートホール', description: 'ノートを70,000回投稿した'),
  'notes80000': (title: 'ノートギャラクシー', description: 'ノートを80,000回投稿した'),
  'notes90000': (title: 'ノートバース', description: 'ノートを90,000回投稿した'),
  'notes100000': (
    title: 'ALL YOUR NOTE ARE BELONG TO US',
    description: 'ノートを100,000回投稿した',
  ),
  'login3': (title: 'ビギナーⅠ', description: '通算ログイン日数が3日'),
  'login7': (title: 'ビギナーⅡ', description: '通算ログイン日数が7日'),
  'login15': (title: 'ビギナーⅢ', description: '通算ログイン日数が15日'),
  'login30': (title: 'ミスキストⅠ', description: '通算ログイン日数が30日'),
  'login60': (title: 'ミスキストⅡ', description: '通算ログイン日数が60日'),
  'login100': (title: 'ミスキストⅢ', description: '通算ログイン日数が100日'),
  'login200': (title: '常連Ⅰ', description: '通算ログイン日数が200日'),
  'login300': (title: '常連Ⅱ', description: '通算ログイン日数が300日'),
  'login400': (title: '常連Ⅲ', description: '通算ログイン日数が400日'),
  'login500': (title: 'ベテランⅠ', description: '通算ログイン日数が500日'),
  'login600': (title: 'ベテランⅡ', description: '通算ログイン日数が600日'),
  'login700': (title: 'ベテランⅢ', description: '通算ログイン日数が700日'),
  'login800': (title: 'ノートマスターⅠ', description: '通算ログイン日数が800日'),
  'login900': (title: 'ノートマスターⅡ', description: '通算ログイン日数が900日'),
  'login1000': (title: 'ノートマスターⅢ', description: '通算ログイン日数が1,000日'),
  'noteClipped1': (title: 'クリップせずにはいられないな', description: '初めてノートをクリップした'),
  'noteFavorited1': (title: '星をみるひと', description: '初めてノートをお気に入りに登録した'),
  'myNoteFavorited1': (title: '星が欲しい', description: '自分のノートが他の人からお気に入りに登録された'),
  'profileFilled': (title: '準備万端', description: 'プロフィール設定を行った'),
  'markedAsCat': (title: '吾輩は猫である', description: 'アカウントをCatとして設定した'),
  'following1': (title: 'はじめてのフォロー', description: '初めてフォローした'),
  'following10': (title: 'ついてく、ついてく', description: 'フォローが10人を超した'),
  'following50': (title: '友達たくさん', description: 'フォローが50人を超した'),
  'following100': (title: '友達100人', description: 'フォローが100人を超した'),
  'following300': (title: '友達過多', description: 'フォローが300人を超した'),
  'followers1': (title: 'はじめてのフォロワー', description: '初めてフォローされた'),
  'followers10': (title: 'フォローミー！', description: 'フォロワーが10人を超した'),
  'followers50': (title: 'ぞろぞろ', description: 'フォロワーが50人を超した'),
  'followers100': (title: '人気者', description: 'フォロワーが100人を超した'),
  'followers300': (title: '一列でお並びください', description: 'フォロワーが300人を超した'),
  'followers500': (title: '基地局', description: 'フォロワーが500人を超した'),
  'followers1000': (title: 'インフルエンサー', description: 'フォロワーが1,000人を超した'),
  'collectAchievements30': (title: '実績コレクター', description: '実績を30個以上獲得した'),
  'viewAchievements3min': (title: '実績好き', description: '実績一覧を3分以上眺め続けた'),
  'iLoveMisskey': (title: 'I Love Misskey', description: '"I ❤ #Misskey"を投稿した'),
  'foundTreasure': (title: '宝探し', description: '隠されたお宝を発見した'),
  'client30min': (title: 'ひとやすみ', description: 'クライアントを起動してから30分以上経過した'),
  'client60min': (title: 'Misskeyの見すぎ', description: 'クライアントを起動してから60分以上経過した'),
  'noteDeletedWithin1min': (
    title: 'いまのなし',
    description: '投稿してから1分以内にその投稿を削除した',
  ),
  'postedAtLateNight': (title: '夜行性', description: '深夜にノートを投稿した'),
  'postedAt0min0sec': (title: '時報', description: '0分0秒にノートを投稿した'),
  'selfQuote': (title: '自己言及', description: '自分のノートを引用した'),
  'htl20npm': (title: '流れるTL', description: 'ホームタイムラインの流速が20npmを越す'),
  'viewInstanceChart': (title: 'アナリスト', description: 'サーバーのチャートを表示した'),
  'outputHelloWorldOnScratchpad': (
    title: 'Hello, world!',
    description: 'スクラッチパッドで hello world を出力した',
  ),
  'open3windows': (title: 'マルチウィンドウ', description: 'ウィンドウを3つ以上開いた状態にした'),
  'driveFolderCircularReference': (
    title: '循環参照',
    description: 'ドライブのフォルダを再帰的な入れ子にしようとした',
  ),
  'reactWithoutRead': (
    title: 'ちゃんと読んだ？',
    description: '100文字以上のテキストを含むノートに投稿されてから3秒以内にリアクションした',
  ),
  'clickedClickHere': (title: 'ここをクリック', description: 'ここをクリックした'),
  'justPlainLucky': (title: '単なるラッキー', description: '10秒ごとに0.005%の確率で獲得'),
  'setNameToSyuilo': (title: '神様コンプレックス', description: '名前を syuilo に設定した'),
  'passedSinceAccountCreated1': (title: '一周年', description: 'アカウント作成から1年経過した'),
  'passedSinceAccountCreated2': (title: '二周年', description: 'アカウント作成から2年経過した'),
  'passedSinceAccountCreated3': (title: '三周年', description: 'アカウント作成から3年経過した'),
  'loggedInOnBirthday': (title: 'ハッピーバースデー', description: '誕生日にログインした'),
  'loggedInOnNewYearsDay': (title: 'あけましておめでとうございます', description: '元日にログインした'),
  'cookieClicked': (title: 'クッキーをクリックするゲーム', description: 'クッキーをクリックした'),
  'brainDiver': (title: 'Brain Diver', description: 'Brain Diverへのリンクを投稿した'),
  'smashTestNotificationButton': (
    title: 'テスト過剰',
    description: '通知のテストをごく短時間のうちに連続して行った',
  ),
  'tutorialCompleted': (title: 'Misskey初心者講座 修了証', description: 'チュートリアルを完了した'),
  'bubbleGameExplodingHead': (title: '🤯', description: 'バブルゲームで最も大きいモノを出した'),
  'bubbleGameDoubleExplodingHead': (
    title: 'ダブル🤯',
    description: 'バブルゲームで最も大きいモノを2つ同時に出した',
  ),
};
